Fix missing fields on new car
frenck/python-vehicle pull request #416
Opened 2023-06-21 13:07 UTC by joostlek

# Proposed Changes

Apparently these fields can be missing from the RDW API.

## Related Issues
https://github.com/home-assistant/core/issues/94920

2023-07-19 07:58 UTC, frenck requested changes

2023-07-19 07:58 UTC, frenck commented on src/vehicle/models.py
> -    ascription_date: date = Field(..., alias="datum_tenaamstelling")
Let's add tests for this case.

2023-08-27 10:18 UTC, joostlek commented
Boop

2023-09-27 08:04 UTC, joostlek commented
Beep

2023-10-20 10:03 UTC, frenck approved these changes

2023-10-20 10:04 UTC, merged